### ISSUE TITLE
Check-in to Hacktoberfest Goa

### ISSUE THREAD

**Issue by salil-naik** [WebDevGoa/hacktoberfest-goa#4]
Hello. Fork the repository and add your name by filling the table in the README.md file in `2020` folder.
Once your PR is approved, your GitHub profile will be displayed in the participant's section. 

Note: _Contributors' images are generated once in a day and it will be cached for later requests._

- [ ] Added my name, mantra and social
- [ ] Formatted the MD file using [Prettier](https://marketplace.visualstudio.com/items?itemName=esbenp.prettier-vscode)

![image](https://user-images.githubusercontent.com/20141508/94778911-af64a400-03e3-11eb-892f-b58c898af052.png)

**Comment by Zinkuth** [comment]
I am willing to take on it!

**Comment by lopeselio** [comment]
added my name, mantra and social #34 

 - [x] Added my name, mantra and social
 - [x] Formatted the MD file using Prettier
